name: Daily Stock Analysis

on:
  schedule:
    # UTC时间，北京时间18:30 = UTC 10:30，周一至周五
    - cron: "30 10 * * 1-5"
  workflow_dispatch: # 支持手动点按钮测试
    inputs:
      force_run:
        description: 强制运行(非交易日也执行)
        default: "false"
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock analysis
        env:
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}openai
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # LLM_PROVIDER: "openai"
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          # OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          STOCK_LIST: ${{ secrets.STOCK_LIST }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
          CUSTOM_WEBHOOK_URLS: ${{ secrets.CUSTOM_WEBHOOK_URLS }}
          TAVILY_API_KEYS: ${{ secrets.TAVILY_API_KEYS }}
          TICKFLOW_API_KEY: ${{ secrets.TICKFLOW_API_KEY }}
          TICKFLOW_PRIORITY: "0"
          EFINANCE_PRIORITY: "1"
          AKSHARE_PRIORITY: "2"
          MARKET_REVIEW_ENABLE: "true"
          SEARXNG_PUBLIC_INSTANCES_ENABLED: "false"
          SEARXNG_BASE_URLS: ""
          FETCHER_REQUEST_DELAY: "2.5"
          ENABLE_EASTMONEY_PATCH: "true"
          MAX_WORKERS: "1"
          # SEARCH_BACKEND 控制搜索后端：tavily / searxng
          SEARCH_BACKEND: "tavily"
        run: |
          if [[ "${{ github.event.inputs.force_run }}" == "true" ]]; then
            python main.py --force-run
          else
            python main.py
          fi

      # 上传报告为 Artifact，不会提交到仓库
      - name: Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: stock‑daily‑report‑${{ github.run_id }}
          path: ./reports/
          retention-days: 7  # 报告保留7天，可自行修改
